import React, { useEffect, useState } from "react";
import { Avatar } from "@mui/material";
import ChatBubbleOutlineOutlinedIcon from "@mui/icons-material/ChatBubbleOutlineOutlined";
import ThumbUpAltOutlinedIcon from "@mui/icons-material/ThumbUpAltOutlined";
import NearMeOutlinedIcon from "@mui/icons-material/NearMeOutlined";
import moment from "moment";
import { useTheme } from "../../ThemeContext";

import "../../styles/Post.css";

function Post({ profilePic, image, username, timestamp, message }) {
  //manage the timeago state which hold the formattted string
  const { theme } = useTheme();
  const [timeAgo, setTime] = useState("");

  //useEffect  with a dependency array meaning it will run when the component mounts and whenever the timestamp value changes.
  useEffect(() => {
    const updateTimeAgo = () => {
      try {
        if (moment(timestamp).isValid()) {
          //parse the timestamp and sets the state timeago to the relative string generated by moment(..)
          setTime(moment(timestamp).fromNow());
        } else {
          throw new Error("Invalid date");
        }
      } catch (err) {
        console.log("Invalid timestamp: ", err);
        setTime("Invalid date");
      }
    };

    // Update immediately on mount
    updateTimeAgo();

    // Set up an interval to update the time ago string every minute (refresh every minute)
    const timeInterval = setInterval(updateTimeAgo, 60000);

    // Cleanup interval on unmount
    return () => clearInterval(timeInterval);
  }, [timestamp]);
  return (
    <div className={`post my_post __post__ ${theme}`} id="_post">
      <div className="post__top">
        <Avatar src={profilePic} className="post__avatar" />
        <div className={`post__topInfo`}>
          <h3 className={`username  __user__ ${theme}`}>{username}</h3>

          <p className={`time __time__ ${theme}`}>{timeAgo}</p>
        </div>
      </div>

      <div className="post__bottom">
        <p className={`text_bottom __text_btm__ ${theme}`}>{message}</p>
      </div>

      <div className="post__image">
        <img src={image} alt="image1" />
      </div>

      <div className="post__options">
        <div className={`post__option btn__hover ${theme}`}>
          <ThumbUpAltOutlinedIcon />
          <p className={`__text__ like ${theme}`}>Like</p>
        </div>
        <div className={`post__option btn__hover ${theme}`}>
          <ChatBubbleOutlineOutlinedIcon />
          <p className={`__text__ comm ${theme}`}>Comment</p>
        </div>

        <div className={`post__option btn__hover ${theme}`}>
          <NearMeOutlinedIcon />
          <p className={`__text__ share ${theme}`}>Share</p>
        </div>
      </div>
    </div>
  );
}

export default Post;
